apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    {{- include "mysql-replication.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: "* 4 * * *"
  timeZone: "Asia/Shanghai"
  jobTemplate:
    metadata:
      labels:
        {{- include "mysql-replication.labels" . | nindent 8 }}
    spec:
      ttlSecondsAfterFinished: 86400 # 一天后清理掉任务
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: workspace
              emptyDir:
                medium: Memory
        
          # 任务队列
          initContainers:
            - name: replication-stop # 暂停主从同步
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["mysql", "-h{{ .Release.Name }}-1.{{ .Release.Name }}-headless", "-uroot", "-e"]
              args:
                - stop slave;
              # 环境变量 
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password

            - name: mysql-dump # 备份数据库到 SQL
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: [
                "mysqlpump",
                "--set-gtid-purged=OFF",
                "-h{{ .Release.Name }}-1.{{ .Release.Name }}-headless",
                "-uroot"
              ]
              args:
                - icampus
                - --result-file=/workspace/dump.sql
              # 环境变量 
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password
              volumeMounts:
                - name: workspace
                  readOnly: false
                  mountPath: /workspace

            - name: mysql-import # 导入 SQL 到数据库
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["bash", "-c"]
              args:
                - mysql -h{{ .Release.Name }}-1.{{ .Release.Name }}-headless -uroot icampus_$(date +%u) < /workspace/dump.sql
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password
              volumeMounts:
                - name: workspace
                  readOnly: true
                  mountPath: /workspace

            - name: replication-start # 恢复主从同步
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["mysql", "-h{{ .Release.Name }}-1.{{ .Release.Name }}-headless", "-uroot", "-e"]
              args:
                - start slave;
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password
            
          containers:
            - name: upload # 备份 SQL
              image: busybox:latest
              command: ["echo"]
              args:
                - done