apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    {{- include "mysql-replication.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: "* 4 * * *"
  timeZone: "Asia/Shanghai"
  jobTemplate:
    metadata:
      labels:
        {{- include "mysql-replication.labels" . | nindent 8 }}
    spec:
      ttlSecondsAfterFinished: 86400 # 一天后清理掉任务
      backoffLimit: 0 # 失败重试次数
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: workspace
              emptyDir:
                medium: Memory
        
          # 任务队列
          initContainers:
            - name: replica-stop # 暂停主从同步
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["mysqladmin", "-h{{ .Release.Name }}-1.{{ .Release.Name }}-headless"]
              args:
                - stop-slave
              # 环境变量 
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password

            - name: mysql-dump # 备份数据库到 SQL
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: [
                "mysqldump",
                "--set-gtid-purged=OFF",
                "--skip-add-drop-table",
                "-h{{ .Release.Name }}-1.{{ .Release.Name }}-headless",
                "-uroot"
              ]
              args:
                - icampus
                - --result-file=/workspace/dump.sql
              # 环境变量 
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password
              volumeMounts:
                - name: workspace
                  readOnly: false
                  mountPath: /workspace

            - name: replica-start # 恢复主从同步
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["mysqladmin", "-h{{ .Release.Name }}-1.{{ .Release.Name }}-headless"]
              args:
                - start-slave
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password

            - name: mysql-drop # 丢弃备份库
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["bash", "-c"]
              args:
                - mysql -h{{ .Release.Name }}-1.{{ .Release.Name }}-headless -uroot -e "DROP DATABASE IF EXISTS {{ .Values.cronjob.database }}_$(date -u +%a);"
              # 环境变量 
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password

            - name: mysql-create # 创建备份库
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["bash", "-c"]
              args:
                - mysql -h{{ .Release.Name }}-1.{{ .Release.Name }}-headless -uroot -e "CREATE DATABASE IF NOT EXISTS {{ .Values.cronjob.database }}_$(date -u +%a) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
              # 环境变量 
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password
            
          containers:
            - name: mysql-import # 导入 SQL 到备份库
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["bash", "-c"]
              args:
                - mysql --verbose -h{{ .Release.Name }}-1.{{ .Release.Name }}-headless -uroot {{ .Values.cronjob.database }}_$(date -u +%a) < /workspace/dump.sql
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-root
                      key: password
              volumeMounts:
                - name: workspace
                  readOnly: true
                  mountPath: /workspace