apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  selector:
    {{- include "mysql-replication.selectorLabels" . | nindent 8 }}
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      {{- include "mysql-replication.selectorLabels" . | nindent 6 }}
  serviceName: "mysql"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        {{- include "mysql-replication.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10

      # 卷定义
      volumes:
        - hostPath:
            path: /etc/localtime
            type: 'File'
          name: host-time

      # 容器组
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["--ignore-db-dir=lost+found"]
          
          # 容器端口
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP

          # 环境变量 
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-root
                  key: password

          # 持久卷挂载
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: data
              readOnly: false
              mountPath: /var/lib/mysql

  # 持久卷申领模版
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 10Gi